# Deploys a Python Azure Function App (classic Consumption) on push to main
name: Build and deploy Python project to Azure Function App - WeatherCrawler

on:
  push:
    branches: [ main ]
    paths: [ 'backend/**' ]
  workflow_dispatch:

env:
  AZURE_FUNCTIONAPP_PACKAGE_PATH: 'backend'
  PYTHON_VERSION: '3.12'  # Match Function App stack version

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      # Install dependencies and create deployment package
      - name: Create deployment package
        run: |
          cd ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}
          python -m pip install --upgrade pip
          pip install -r requirements.txt -t .
          echo "Creating deployment ZIP package..."
          zip -r ../deployment-package.zip . -x "*.git*" "*__pycache__*" "*.pyc"

      # Upload the ZIP package
      - name: Upload deployment package
        uses: actions/upload-artifact@v4
        with:
          name: python-deployment-package
          path: deployment-package.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download deployment package
        uses: actions/download-artifact@v4
        with:
          name: python-deployment-package
          path: ./

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_A3490156602A436C9BFC3C90FEA2A86C }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_2439C3A29D1445558E2751C770A84E69 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_61D46500869946E4B2B3BC07386E36B0 }}

      # Set WEBSITE_RUN_FROM_PACKAGE = 1 for ZIP deployment
      - name: Configure Function App for ZIP deployment
        run: |
          echo "Setting WEBSITE_RUN_FROM_PACKAGE=1 for ZIP deployment..."
          az functionapp config appsettings set \
            --name 'WeatherCrawler' \
            --resource-group 'climaguate_rg' \
            --settings WEBSITE_RUN_FROM_PACKAGE=1

      - name: Deploy ZIP package to Azure Functions
        uses: Azure/functions-action@v1
        with:
          app-name: 'WeatherCrawler'
          slot-name: 'Production'
          package: ./deployment-package.zip
